name: fixpals_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  google_fonts: 2.3.2
  http: 0.13.4
  latlong2: 0.8.1
  shared_preferences: 2.0.15
  geolocator: 8.2.1
  expandable: 5.0.1
  carousel_slider: 4.1.1
  flutter_map: 0.14.0
  permission_handler: 8.2.5
  flutter_phone_direct_caller: ^2.1.1
  flutter_background_service: ^2.1.3
  flutter_background_service_android: ^2.0.3
  web_socket_channel: ^2.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/json_files/
  uses-material-design: true

